POST http://localhost:8080/v1/student
Content-Type: application/json

{
  "fullName" : "Juan Lopez"
}

###

GET http://localhost:8080/v1/student/?id=2
Content-Type: application/json

###


PUT http://localhost:8080/v1/student
Content-Type: application/json

{
  "studentId": 3,
"fullName" : "Juan Lopez Perez"
}

###

DELETE http://localhost:8080/v1/student/?id=3
Content-Type: application/json

###